"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { publishVehicleSchema, type PublishVehicleData } from "@/lib/validations/vehicle";

export interface PublishVehicleResult {
  error?: string;
  vehicleId?: string;
}

export async function publishVehicle(
  data: PublishVehicleData
): Promise<PublishVehicleResult> {
  const parsed = publishVehicleSchema.safeParse(data);
  if (!parsed.success) {
    return { error: parsed.error.issues[0].message };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "No autenticado" };
  }

  const {
    photoStoragePaths,
    coverPhotoIndex,
    videoStoragePath,
    ...vehicleFields
  } = parsed.data;

  // Insert vehicle (slug is auto-generated by DB trigger)
  const { data: vehicle, error: vehicleError } = await supabase
    .from("vehicles")
    .insert({
      user_id: user.id,
      brand: vehicleFields.brand,
      model: vehicleFields.model,
      year: vehicleFields.year,
      mileage: vehicleFields.mileage,
      color: vehicleFields.color,
      transmission: vehicleFields.transmission,
      fuel: vehicleFields.fuel,
      plate: vehicleFields.plate || null,
      engine: vehicleFields.engine || null,
      doors: vehicleFields.doors,
      price: vehicleFields.price,
      description: vehicleFields.description || null,
      conditions: vehicleFields.conditions,
      status: "active",
      published_at: new Date().toISOString(),
      expires_at: new Date(
        Date.now() + 60 * 24 * 60 * 60 * 1000
      ).toISOString(), // 60 days
    })
    .select("id")
    .single();

  if (vehicleError || !vehicle) {
    console.error("Vehicle insert error:", vehicleError);
    return { error: "Error al crear el vehículo. Intenta de nuevo." };
  }

  // Build storage base URL
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;

  // Insert photo media records
  const photoRecords = photoStoragePaths.map((storagePath, index) => ({
    vehicle_id: vehicle.id,
    type: "photo" as const,
    url: `${supabaseUrl}/storage/v1/object/public/vehicles/${storagePath}`,
    storage_path: storagePath,
    display_order: index,
    is_cover: index === coverPhotoIndex,
  }));

  if (photoRecords.length > 0) {
    const { error: photoError } = await supabase
      .from("media")
      .insert(photoRecords);
    if (photoError) {
      console.error("Photo media insert error:", photoError);
    }
  }

  // Insert video media record
  if (videoStoragePath) {
    const { error: videoError } = await supabase.from("media").insert({
      vehicle_id: vehicle.id,
      type: "video",
      url: `${supabaseUrl}/storage/v1/object/public/vehicles/${videoStoragePath}`,
      storage_path: videoStoragePath,
      display_order: 0,
      is_cover: false,
    });
    if (videoError) {
      console.error("Video media insert error:", videoError);
    }
  }

  redirect("/dashboard?published=true");
}

export interface MarkAsSoldResult {
  success: boolean;
  error?: string;
}

export async function markVehicleAsSold(
  vehicleId: string
): Promise<MarkAsSoldResult> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "No autenticado" };
  }

  const { error } = await supabase
    .from("vehicles")
    .update({
      status: "sold",
      sold_at: new Date().toISOString(),
    })
    .eq("id", vehicleId)
    .eq("user_id", user.id);

  if (error) {
    console.error("Mark as sold error:", error);
    return { success: false, error: "Error al marcar como vendido." };
  }

  return { success: true };
}
