"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import {
  publishVehicleSchema,
  type PublishVehicleData,
  updateVehicleSchema,
  type UpdateVehicleData,
} from "@/lib/validations/vehicle";
import { sendEmail } from "@/lib/email/resend";
import { vehiclePublishedEmail } from "@/lib/email/templates/vehicle-published";
import { checkRateLimit } from "@/lib/security/rate-limit";
import { sanitizeString } from "@/lib/security/sanitize";
import type { Profile } from "@/types";

export interface PublishVehicleResult {
  error?: string;
  vehicleId?: string;
}

export async function publishVehicle(
  data: PublishVehicleData
): Promise<PublishVehicleResult> {
  const parsed = publishVehicleSchema.safeParse(data);
  if (!parsed.success) {
    return { error: parsed.error.issues[0].message };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "No autenticado" };
  }

  // Rate limit: max 3 publications per hour per user
  const { allowed } = checkRateLimit(`publish:${user.id}`, {
    maxRequests: 3,
    windowMs: 60 * 60 * 1000,
  });
  if (!allowed) {
    return { error: "Has publicado demasiados vehículos. Intenta más tarde." };
  }

  const {
    photoStoragePaths,
    coverPhotoIndex,
    videoStoragePath,
    delivery,
    ...vehicleFields
  } = parsed.data;

  // Insert vehicle as draft (slug is auto-generated by DB trigger)
  // Vehicle stays draft until payment is confirmed via webhook
  const { data: vehicle, error: vehicleError } = await supabase
    .from("vehicles")
    .insert({
      user_id: user.id,
      brand: vehicleFields.brand,
      model: vehicleFields.model,
      year: vehicleFields.year,
      mileage: vehicleFields.mileage,
      color: vehicleFields.color,
      transmission: vehicleFields.transmission,
      fuel: vehicleFields.fuel,
      plate: vehicleFields.plate || null,
      engine: vehicleFields.engine || null,
      doors: vehicleFields.doors,
      price: vehicleFields.price,
      description: vehicleFields.description ? sanitizeString(vehicleFields.description) : null,
      conditions: vehicleFields.conditions,
      status: "draft",
    })
    .select("id, slug")
    .single();

  if (vehicleError || !vehicle) {
    console.error("Vehicle insert error:", vehicleError);
    return { error: "Error al crear el vehículo. Intenta de nuevo." };
  }

  // Build storage base URL
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;

  // Insert photo media records
  const photoRecords = photoStoragePaths.map((storagePath, index) => ({
    vehicle_id: vehicle.id,
    type: "photo" as const,
    url: `${supabaseUrl}/storage/v1/object/public/vehicles/${storagePath}`,
    storage_path: storagePath,
    display_order: index,
    is_cover: index === coverPhotoIndex,
  }));

  if (photoRecords.length > 0) {
    const { error: photoError } = await supabase
      .from("media")
      .insert(photoRecords);
    if (photoError) {
      console.error("Photo media insert error:", photoError);
    }
  }

  // Insert video media record
  if (videoStoragePath) {
    const { error: videoError } = await supabase.from("media").insert({
      vehicle_id: vehicle.id,
      type: "video",
      url: `${supabaseUrl}/storage/v1/object/public/vehicles/${videoStoragePath}`,
      storage_path: videoStoragePath,
      display_order: 0,
      is_cover: false,
    });
    if (videoError) {
      console.error("Video media insert error:", videoError);
    }
  }

  // Create QR order with delivery data
  if (delivery) {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://carros-usados.vercel.app";
    const qrUrl = `${appUrl}/v/${vehicle.slug}`;

    const { error: qrOrderError } = await supabase.from("qr_orders").insert({
      vehicle_id: vehicle.id,
      qr_url: qrUrl,
      status: "pending",
      delivery_address: delivery.address,
      delivery_city: delivery.city,
      delivery_phone: delivery.phone,
      preferred_time: delivery.preferredTime,
      delivery_notes: delivery.notes || null,
    });
    if (qrOrderError) {
      console.error("QR order insert error:", qrOrderError);
    }
  }

  return { vehicleId: vehicle.id };
}

/**
 * Activate a vehicle after payment confirmation.
 * Idempotent: only activates if vehicle is currently a draft.
 * Uses admin client to bypass RLS (called from webhook context).
 */
export async function activateVehicle(vehicleId: string): Promise<{ success: boolean; error?: string }> {
  const supabase = createAdminClient();

  // Only activate drafts (idempotent for webhook retries)
  const { data: vehicle, error: fetchError } = await supabase
    .from("vehicles")
    .select("id, status, user_id, brand, model, year, slug, price, transmission, fuel")
    .eq("id", vehicleId)
    .single();

  if (fetchError || !vehicle) {
    return { success: false, error: "Vehicle not found" };
  }

  if (vehicle.status !== "draft") {
    // Already activated — idempotent success
    return { success: true };
  }

  const now = new Date();
  const expiresAt = new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000); // 60 days

  const { error: updateError } = await supabase
    .from("vehicles")
    .update({
      status: "active",
      published_at: now.toISOString(),
      expires_at: expiresAt.toISOString(),
    })
    .eq("id", vehicleId);

  if (updateError) {
    console.error("Activate vehicle error:", updateError);
    return { success: false, error: "Failed to activate vehicle" };
  }

  // Fire-and-forget: match against search alerts
  import("@/lib/alerts/match-alerts").then(({ matchAndNotifyAlerts }) =>
    matchAndNotifyAlerts(vehicle).catch((err) => console.error("Alert matching error:", err))
  );

  // Send publication email
  try {
    const { data: profile } = await supabase
      .from("profiles")
      .select("email, full_name")
      .eq("id", vehicle.user_id)
      .single();

    const typedProfile = profile as Pick<Profile, "email" | "full_name"> | null;
    if (typedProfile?.email) {
      const { subject, html } = vehiclePublishedEmail(
        typedProfile.full_name || "Usuario",
        vehicle.brand,
        vehicle.model,
        vehicle.year,
        vehicle.slug
      );
      await sendEmail(typedProfile.email, subject, html);
    }
  } catch (emailErr) {
    console.error("Publication email error:", emailErr);
  }

  return { success: true };
}

export interface MarkAsSoldResult {
  success: boolean;
  error?: string;
}

export async function markVehicleAsSold(
  vehicleId: string
): Promise<MarkAsSoldResult> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "No autenticado" };
  }

  const { error } = await supabase
    .from("vehicles")
    .update({
      status: "sold",
      sold_at: new Date().toISOString(),
    })
    .eq("id", vehicleId)
    .eq("user_id", user.id);

  if (error) {
    console.error("Mark as sold error:", error);
    return { success: false, error: "Error al marcar como vendido." };
  }

  return { success: true };
}

export interface RenewVehicleResult {
  success: boolean;
  error?: string;
}

export async function renewVehicle(
  vehicleId: string
): Promise<RenewVehicleResult> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "No autenticado" };
  }

  const { error } = await supabase
    .from("vehicles")
    .update({
      status: "active",
      expires_at: new Date(
        Date.now() + 60 * 24 * 60 * 60 * 1000
      ).toISOString(), // 60 days from now
    })
    .eq("id", vehicleId)
    .eq("user_id", user.id);

  if (error) {
    console.error("Renew vehicle error:", error);
    return { success: false, error: "Error al renovar la publicación." };
  }

  revalidatePath(`/dashboard/vehicles/${vehicleId}`);
  revalidatePath("/dashboard/vehicles");
  return { success: true };
}

export interface UpdateVehicleResult {
  success: boolean;
  error?: string;
}

export async function updateVehicle(
  data: UpdateVehicleData
): Promise<UpdateVehicleResult> {
  const parsed = updateVehicleSchema.safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0].message };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "No autenticado" };
  }

  // Verify ownership and editable status
  const { data: vehicle, error: fetchError } = await supabase
    .from("vehicles")
    .select("id, slug, status, user_id")
    .eq("id", parsed.data.vehicleId)
    .eq("user_id", user.id)
    .single();

  if (fetchError || !vehicle) {
    return { success: false, error: "Vehículo no encontrado" };
  }

  const v = vehicle as { id: string; slug: string; status: string; user_id: string };

  if (v.status !== "active" && v.status !== "expired") {
    return { success: false, error: "Solo puedes editar vehículos activos o vencidos" };
  }

  // Validate price against AI report if price changed
  if (parsed.data.price !== undefined) {
    const { data: aiReport } = await supabase
      .from("ai_price_reports")
      .select("market_price_low, market_price_high")
      .eq("vehicle_id", v.id)
      .order("generated_at", { ascending: false })
      .limit(1)
      .single();

    const report = aiReport as { market_price_low: number | null; market_price_high: number | null } | null;

    if (report?.market_price_low != null) {
      if (parsed.data.price < report.market_price_low) {
        return {
          success: false,
          error: `El precio no puede ser menor a $${report.market_price_low.toLocaleString("en-US")} (mínimo del reporte IA)`,
        };
      }
    }
  }

  // Build vehicle update object (only changed fields)
  const vehicleUpdate: Record<string, unknown> = {};
  if (parsed.data.price !== undefined) vehicleUpdate.price = parsed.data.price;
  if (parsed.data.description !== undefined) {
    vehicleUpdate.description = parsed.data.description
      ? sanitizeString(parsed.data.description)
      : null;
  }
  if (parsed.data.conditions !== undefined) vehicleUpdate.conditions = parsed.data.conditions;

  // Update vehicle record if any fields changed
  if (Object.keys(vehicleUpdate).length > 0) {
    const { error: updateError } = await supabase
      .from("vehicles")
      .update(vehicleUpdate)
      .eq("id", v.id)
      .eq("user_id", user.id);

    if (updateError) {
      console.error("Update vehicle error:", updateError);
      return { success: false, error: "Error al actualizar el vehículo" };
    }
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;

  // Handle removed photos
  if (parsed.data.removedPhotoStoragePaths && parsed.data.removedPhotoStoragePaths.length > 0) {
    // Delete media records
    for (const path of parsed.data.removedPhotoStoragePaths) {
      await supabase
        .from("media")
        .delete()
        .eq("vehicle_id", v.id)
        .eq("storage_path", path);
    }
    // Delete from storage
    await supabase.storage
      .from("vehicles")
      .remove(parsed.data.removedPhotoStoragePaths);
  }

  // Handle photo reorder + new photos
  if (parsed.data.photoStoragePaths && parsed.data.coverPhotoIndex !== undefined) {
    const coverIndex = parsed.data.coverPhotoIndex;
    for (let i = 0; i < parsed.data.photoStoragePaths.length; i++) {
      const path = parsed.data.photoStoragePaths[i];
      const url = `${supabaseUrl}/storage/v1/object/public/vehicles/${path}`;

      // Try to update existing media record
      const { data: existing } = await supabase
        .from("media")
        .select("id")
        .eq("vehicle_id", v.id)
        .eq("storage_path", path)
        .single();

      if (existing) {
        // Update display order and cover flag
        await supabase
          .from("media")
          .update({ display_order: i, is_cover: i === coverIndex })
          .eq("id", (existing as { id: string }).id);
      } else {
        // Insert new media record
        await supabase.from("media").insert({
          vehicle_id: v.id,
          type: "photo" as const,
          url,
          storage_path: path,
          display_order: i,
          is_cover: i === coverIndex,
        });
      }
    }
  }

  // Handle removed video
  if (parsed.data.removedVideoStoragePath) {
    await supabase
      .from("media")
      .delete()
      .eq("vehicle_id", v.id)
      .eq("storage_path", parsed.data.removedVideoStoragePath);
    await supabase.storage
      .from("vehicles")
      .remove([parsed.data.removedVideoStoragePath]);
  }

  // Handle new video
  if (parsed.data.videoStoragePath) {
    const url = `${supabaseUrl}/storage/v1/object/public/vehicles/${parsed.data.videoStoragePath}`;
    await supabase.from("media").insert({
      vehicle_id: v.id,
      type: "video" as const,
      url,
      storage_path: parsed.data.videoStoragePath,
      display_order: 0,
      is_cover: false,
    });
  }

  // Revalidate pages
  revalidatePath(`/dashboard/vehicles/${v.id}`);
  revalidatePath("/dashboard/vehicles");
  revalidatePath(`/${v.slug}`);

  return { success: true };
}
